name: ci
on:
    release:
        types:
          - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install mkdocs-material
      - run: mkdocs build

      - name: Generate Json Data
        run: |
            cd parse_data_to_lsp
            python to_parse.py

      - name: Zip manual
        run: |
          cd site
          mkdir -p csound_resources
          mkdir -p csound_resources/opcodes
          mkdir -p csound_resources/examples
          cp -r ../parse_data_to_lsp/json_data/* csound_resources/
          cp -r ../docs/opcodes/* csound_resources/opcodes/
          cp -r ../docs/examples/* csound_resources/examples/
          zip -r ../csound_manual-html.zip .

      - name: Create release and upload asset
        uses: softprops/action-gh-release@v1
        with:
            tag_name: ${{ github.event.release.tag_name }}
            files: csound_manual-html.zip
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
