name: ci
on:
    release:
        types:
          - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install mkdocs-material
      - run: mkdocs build

      - name: Zip manual
        run: |
          cd site
          zip -r ../csound_manual-html.zip .

      - name: Create release and upload asset
        uses: softprops/action-gh-release@v1
        with:
            tag_name: ${{ github.event.release.tag_name }}
            files: csound_manual-html.zip
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
